name: 💡 Feature Request - Level Editor
description: Create an issue for a feature request in the level editor
title: "Enter a precise title here!"
labels: [level editor, enhancement]
body:
  - type: textarea
    id: featurerequest-level-text1
    attributes:
      label: Enter your feature description.
      placeholder: What is missing? What could be improved?
    validations:
      required: true