name: 💡 Feature Request - Model Editor
description: Create an issue for a feature request in the model editor
title: "Enter a precise title here!"
labels: [model editor, enhancement]
body:
  - type: textarea
    id: featurerequest-model-text1
    attributes:
      label: Enter your feature description.
      placeholder: What is missing? What could be improved?
    validations:
      required: true